version: '2'
services:
  web:
    build: .
    image: flask-network
    command: python Blog/flask_blog.py
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    depends_on:
    - db
  db:
    image: postgres:10.2
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flaskpass
      - POSTGRES_DB=flask_db

    volumes:
    - .:/tmp/data/
    expose:
      - 5432