version: '2'
services:
  web:
    build: .
    image: flask-network
    command: python Blog/flask_blog.py
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    depends_on:
    - db
  db:
    image: postgres:10.2
    volumes:
    - .:/tmp/data/